name: 功能建议
description: 对本项目提出一个功能建议
title: "[功能建议]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢提出功能建议，我们将仔细考虑！
  - type: textarea
    id: related-problem
    attributes:
      label: 你的功能建议是否和某个问题相关？
      description: 清晰并简洁地描述问题是什么，例如，当我...时，我总是感到困扰。
    validations:
      required: false
  - type: textarea
    id: desired-solution
    attributes:
      label: 你希望看到什么解决方案？
      description: 清晰并简洁地描述你希望发生的事情。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 你考虑过哪些替代方案？
      description: 清晰并简洁地描述你考虑过的任何替代解决方案或功能。
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 你有其他上下文或截图吗？
      description: 在此处添加有关功能请求的任何其他上下文或截图。
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 意向参与贡献
      options:
        - label: 我有意向参与具体功能的开发实现并将代码贡献回到上游社区
          required: false

name: Bug 反馈
description: 当你在代码中发现了一个 Bug，导致应用崩溃或抛出异常，或者有一个组件存在问题，或者某些地方看起来不对劲。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢对项目的支持与关注。在提出问题之前，请确保你已查看相关开发或使用文档：
        - https://...
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经搜索过现有的问题 (https://gitee.com/../../issues)
          required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题，如涉及代码，可提供一个最小代码示例，并使用反引号```附上它
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期结果
      description: 请告诉我们你预期会发生什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际结果
      description: 请告诉我们实际发生了什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或视频
      description: 如果可以的话，上传任何关于 bug 的截图。
      value: |
        [在这里上传图片]
  - type: dropdown
    id: version
    attributes:
      label: 版本
      description: 你当前正在使用我们软件的哪个版本/分支？
      options:
        - main(默认)
    validations:
      required: true